version: "3.2"

services:
  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile
    image: "backend"    
    ports:
      - 4000:3000
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - internal-network
      - external-network    
  postgres:
    image: "postgres:12"
    env_file:
      - .env
    volumes:    
     - ./pg-data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - internal-network
  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    image: "frontend"
    ports:
      - 8081:80
    networks:
      - external-network

networks:
  internal-network:
    driver: bridge
    internal: true
  external-network:
    driver: bridge
    
   